### ISSUE TITLE
[Frontend] Create design prototype for main page

### ISSUE THREAD

**Issue by BoxBoxJason** [BoxBoxJason/JukeBox#13]
# Create design prototype for main page

### Definition
Create a design prototype for the main page. Define the color theme. Define the position of the 
Should differentiate mobile (smartphone) and screen display !!!

### Definition of done
- Have the main page design with
    - [x] JukeBox logo including the PLAY button
    - [x] Access to log in / register option
    - [x] DropDown menu with quick access to planning section, queue section, about section, logout option (if logged in)

**Comment by BoxBoxJason** [comment]
duplicate

**Comment by Mathisadi** [comment]
Preview of the main page done and can be seen at : https://www.canva.com/design/DAGTpHDUaIQ/7PmHQO0yOZdz1e-adZT7ag/edit
