### ISSUE TITLE
[Frontend] Create design prototype for navigation top / sidebar

### ISSUE THREAD

**Issue by BoxBoxJason** [BoxBoxJason/JukeBox#15]
# Create design prototype for navigation top / sidebar

### Definition
Design the navigation top bar for the website
Design the navigation sidebar (dropdown menu) for the website

### Definition of done
- [x] Top bar designed
- [x] Sidebar designed

**Comment by Mathisadi** [comment]
Prototype for navigation top / sidebar done and can be seen at : https://www.canva.com/design/DAGTpHDUaIQ/7PmHQO0yOZdz1e-adZT7ag/edit
