### ISSUE TITLE
[Frontend] Implement JukeBox user auth widgets

### ISSUE THREAD

**Issue by BoxBoxJason** [BoxBoxJason/JukeBox#4]
# Implement JukeBox user auth widgets

### Definition
Create JukeBox user registration & login widgets
Keep style consistent between them

### Definition of done
- [x] Login is available
- [x] Register is available
- [ ] Page is protected from bot attacks

**Comment by Mathisadi** [comment]
The widget are implemented and operationnal

! Bot attack
