### ISSUE TITLE
[Frontend] Implement Design JukeBox main page

### ISSUE THREAD

**Issue by BoxBoxJason** [BoxBoxJason/JukeBox#7]
# Implement Design JukeBox main page

### Definition
Implement the design the main page for the JukeBox, the main page should display the following informations:
- Interactive chat window
- Current music title
- Parameters the model is currently applying to create the music (if the user is logged in)
- Music rythm / chords variation animation 

### Definition of done
- [ ] Can access chat and post stuff in it (if logged in)
- [ ] Can read the current music title
- [ ] Can read the parameters that the model uses to generate the music (if logged in)
- [ ] Display music ryhtm / chords variation in a pleasant way

**Comment by Mathisadi** [comment]
The aspect of the main page is operational, only the connection with back is needed
